/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionedt.views;

/**
 *
 * @author diary
 */
import com.mycompany.gestionedt.controllers.ClasseControllers;
import com.mycompany.gestionedt.models.ClasseModels;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class classeViews extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(classeViews.class.getName());

    /**
     * Creates new form classeViews
     */
    public classeViews() {
        initComponents();
        refreshClasseTable();
    }
    
    private void refreshClasseTable() {
        try {
            ClasseControllers controller = new ClasseControllers();
            ArrayList<ClasseModels> classes = controller.getAllClasses();

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Classe");
            model.addColumn("Niveau");

            for (ClasseModels classe : classes) {
                model.addRow(new Object[]{
                    classe.getIdclasse(),
                    classe.getNiveau()
                });
            }

            classeTable.setModel(model);
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Erreur lors du rafraîchissement de la table : " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Erreur lors du chargement des classes : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idclasseTextField = new javax.swing.JTextField();
        niveauComboBox = new javax.swing.JComboBox<>();
        addClasseButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        classeTable = new javax.swing.JTable();
        editClasseButton = new javax.swing.JButton();
        deleteClasseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("id classe");

        jLabel2.setText("Niveau");

        niveauComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L1 IG", "L1 Pro", "L2 IG", "L2 ASR", "L2 GB", "L3 IG", "L3 GB", "L3 ASR", "M1 IG", "M1 ASR", "M1GB", "M2 IG", "M2ASR", "M2GB" }));

        addClasseButton.setText("jButton1");
        addClasseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClasseButtonActionPerformed(evt);
            }
        });

        jButton2.setText("cancel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addClasseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(niveauComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idclasseTextField)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idclasseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(niveauComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addClasseButton)
                    .addComponent(jButton2))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        classeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id Salle", "Niveau"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(classeTable);

        editClasseButton.setText("jButton1");
        editClasseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editClasseButtonActionPerformed(evt);
            }
        });

        deleteClasseButton.setText("jButton3");
        deleteClasseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClasseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(editClasseButton)
                        .addGap(69, 69, 69)
                        .addComponent(deleteClasseButton)))
                .addContainerGap(818, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editClasseButton)
                            .addComponent(deleteClasseButton))))
                .addContainerGap(341, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addClasseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClasseButtonActionPerformed
        // TODO add your handling code here:
    String idClasseStr = idclasseTextField.getText().trim();
        String niveau = niveauComboBox.getSelectedItem() != null ? niveauComboBox.getSelectedItem().toString().trim() : "";

        if (!idClasseStr.isEmpty() && !niveau.isEmpty()) {
            try {
                int idClasse = Integer.parseInt(idClasseStr);

                ClasseControllers controller = new ClasseControllers();
                if (addClasseButton.getText().equals("Save")) {
                    ClasseModels classe = new ClasseModels(idClasse, niveau);
                    controller.updateClasse(classe);
                    JOptionPane.showMessageDialog(this, "Classe mise à jour avec succès ! ID : " + idClasse);
                    addClasseButton.setText("Ajouter");
                    idclasseTextField.setEditable(true);
                } else {
                    ClasseModels classe = controller.ajouterClasse(idClasse, niveau);
                    JOptionPane.showMessageDialog(this, "Classe ajoutée avec succès ! ID : " + classe.getIdclasse());
                }

                clearClasseFields();
                refreshClasseTable();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ID Classe doit être un nombre valide !", "Erreur", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                logger.log(Level.SEVERE, "Erreur lors de l'ajout/mise à jour : " + e.getMessage());
                JOptionPane.showMessageDialog(this, "Une erreur est survenue : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addClasseButtonActionPerformed

    private void editClasseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editClasseButtonActionPerformed
        // TODO add your handling code here:
      int selectedRow = classeTable.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) classeTable.getModel();
            String idClasseStr = model.getValueAt(selectedRow, 0).toString();
            String niveau = model.getValueAt(selectedRow, 1).toString();

            idclasseTextField.setText(idClasseStr);
            idclasseTextField.setEditable(false);
            niveauComboBox.setSelectedItem(niveau);
            addClasseButton.setText("Save");
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une classe à modifier !", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editClasseButtonActionPerformed

    private void deleteClasseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteClasseButtonActionPerformed
        // TODO add your handling code here:
       int selectedRow = classeTable.getSelectedRow();
        logger.info("Ligne sélectionnée : " + selectedRow); // Ajout pour débogage
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) classeTable.getModel();
            String idClasseStr = model.getValueAt(selectedRow, 0).toString();
            int idClasse = Integer.parseInt(idClasseStr);

            int confirm = JOptionPane.showConfirmDialog(this, "Êtes-vous sûr de vouloir supprimer la classe avec ID " + idClasse + " ?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    ClasseControllers controller = new ClasseControllers();
                    controller.deleteClasse(idClasse);
                    refreshClasseTable();
                    JOptionPane.showMessageDialog(this, "Classe supprimée avec succès !");
                } catch (Exception e) {
                    logger.log(Level.SEVERE, "Erreur lors de la suppression : " + e.getMessage());
                    JOptionPane.showMessageDialog(this, "Une erreur est survenue : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une classe à supprimer !", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_deleteClasseButtonActionPerformed
private void clearClasseFields() {
        idclasseTextField.setText("");
        niveauComboBox.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
   
        java.awt.EventQueue.invokeLater(() -> new classeViews().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClasseButton;
    private javax.swing.JTable classeTable;
    private javax.swing.JButton deleteClasseButton;
    private javax.swing.JButton editClasseButton;
    private javax.swing.JTextField idclasseTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> niveauComboBox;
    // End of variables declaration//GEN-END:variables
}
