/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionedt.views;

/**
 *
 * @author diary
 */
import com.mycompany.gestionedt.controllers.EdtControllers;
import com.mycompany.gestionedt.models.EdtModels;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import java.util.Date;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class edtViews extends javax.swing.JFrame {
    private JSpinner dateSpinner;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(edtViews.class.getName());

    /**
     * Creates new form edtViews
     */
    public edtViews() {
        initComponents();
       dateSpinner = new JSpinner(new SpinnerDateModel(new Date(), null, null, Calendar.DAY_OF_MONTH));
    JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(dateSpinner, "yyyy-MM-dd HH:mm:ss");
    dateSpinner.setEditor(timeEditor);
    dateSpinner.setBounds(40, 520, 200, 30); // Ajuste la position, voir point 2
    getContentPane().add(dateSpinner);
    
    
     refreshEdtTable();
    }
    
    private void refreshEdtTable() {
        try {
            EdtControllers controller = new EdtControllers();
            ArrayList<EdtModels> edts = controller.getAllEdts();

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID EDT");
            model.addColumn("ID Salle");
            model.addColumn("ID Prof");
            model.addColumn("ID Classe");
            model.addColumn("Cours");
            model.addColumn("Date");

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            for (EdtModels edt : edts) {
                model.addRow(new Object[]{
                    edt.getIdEDT(),
                    edt.getIDSalle(),
                    edt.getIdProf(),
                    edt.getIDClasse(),
                    edt.getCours(),
                    (edt.getDate() != null) ? dateFormat.format(edt.getDate()) : ""
                });
            }

            edtTable.setModel(model);
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Erreur lors du rafraîchissement de la table : " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Erreur lors du chargement des emplois : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idedtTextField = new javax.swing.JTextField();
        idsalleTextField = new javax.swing.JTextField();
        idprofTextField = new javax.swing.JTextField();
        idclasseTextField = new javax.swing.JTextField();
        coursTextField = new javax.swing.JTextField();
        addEdtButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtTable = new javax.swing.JTable();
        editEdtbutton = new javax.swing.JButton();
        deleteEdtButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1800, 1000));
        setResizable(false);

        jLabel1.setText("id EDT");

        jLabel2.setText("id salle");

        jLabel3.setText("id Prof");

        jLabel4.setText("id classe");

        jLabel5.setText("Cours");

        jLabel6.setText("date");

        addEdtButton.setText("ADD");
        addEdtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEdtButtonActionPerformed(evt);
            }
        });

        jButton2.setText("CANCEL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coursTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idclasseTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addComponent(idprofTextField)
                                .addComponent(idsalleTextField)
                                .addComponent(idedtTextField)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addEdtButton)
                        .addGap(39, 39, 39)
                        .addComponent(jButton2)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idedtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idsalleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idprofTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idclasseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coursTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEdtButton)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        edtTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edtTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id edt", "id Salle", "idProf", "id Classe", "Cours", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(edtTable);

        editEdtbutton.setText("EDIT");
        editEdtbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEdtbuttonActionPerformed(evt);
            }
        });

        deleteEdtButton.setText("Delete");
        deleteEdtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEdtButtonActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(editEdtbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteEdtButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteEdtButton)
                    .addComponent(editEdtbutton))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEdtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEdtButtonActionPerformed
        // TODO add your handling code here:
    String idEDT = idedtTextField.getText().trim();
    String idSalleStr = idsalleTextField.getText().trim();
    String idProf = idprofTextField.getText().trim();
    String IDClasse = idclasseTextField.getText().trim();
    String Cours = coursTextField.getText().trim();
    Date selectedDate = (Date) dateSpinner.getValue();
    java.sql.Timestamp Date = new java.sql.Timestamp(selectedDate.getTime());

    if (!idEDT.isEmpty() && !idSalleStr.isEmpty() && !idProf.isEmpty() && !IDClasse.isEmpty() && !Cours.isEmpty()) {
        try {
            int IDSalle = Integer.parseInt(idSalleStr);

            EdtControllers controller = new EdtControllers();
            if (addEdtButton.getText().equals("Save")) {
                EdtModels edt = new EdtModels(idEDT, IDSalle, idProf, IDClasse, Cours, Date);
                controller.updateEdt(edt);
                JOptionPane.showMessageDialog(this, "Emploi mis à jour avec succès ! ID : " + idEDT);
                addEdtButton.setText("Ajouter");
                idedtTextField.setEditable(true);
            } else {
                EdtModels edt = controller.ajouterEdt(idEDT, IDSalle, idProf, IDClasse, Cours, Date);
                JOptionPane.showMessageDialog(this, "Emploi ajouté avec succès ! ID : " + edt.getIdEDT());
            }

            clearEdtFields();
            refreshEdtTable();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID Salle doit être un nombre valide !", "Erreur", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Erreur lors de l'ajout/mise à jour : " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Une erreur est survenue : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !", "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_addEdtButtonActionPerformed

    private void editEdtbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEdtbuttonActionPerformed
        // TODO add your handling code here:
        int selectedRow = edtTable.getSelectedRow();
    if (selectedRow != -1) {
        DefaultTableModel model = (DefaultTableModel) edtTable.getModel();
        String idEDT = model.getValueAt(selectedRow, 0).toString();
        String IDSalleStr = model.getValueAt(selectedRow, 1).toString();
        String idProf = model.getValueAt(selectedRow, 2).toString();
        String IDClasse = model.getValueAt(selectedRow, 3).toString();
        String Cours = model.getValueAt(selectedRow, 4).toString();
        String dateStr = model.getValueAt(selectedRow, 5).toString();
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Date date = dateFormat.parse(dateStr);
            dateSpinner.setValue(date);
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Erreur lors du parsing de la date : " + e.getMessage());
        }

        idedtTextField.setText(idEDT);
        idsalleTextField.setEditable(false);
        idsalleTextField.setText(IDSalleStr);
        idprofTextField.setText(idProf);
        idclasseTextField.setText(IDClasse);
        coursTextField.setText(Cours);
        addEdtButton.setText("Save");
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un emploi à modifier !", "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_editEdtbuttonActionPerformed

    private void deleteEdtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEdtButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = edtTable.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) edtTable.getModel();
            String idEDT = model.getValueAt(selectedRow, 0).toString();

            int confirm = JOptionPane.showConfirmDialog(this, "Êtes-vous sûr de vouloir supprimer l'emploi avec ID " + idEDT + " ?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    EdtControllers controller = new EdtControllers();
                    controller.deleteEdt(idEDT);
                    refreshEdtTable();
                    JOptionPane.showMessageDialog(this, "Emploi supprimé avec succès !");
                } catch (Exception e) {
                    logger.log(Level.SEVERE, "Erreur lors de la suppression : " + e.getMessage());
                    JOptionPane.showMessageDialog(this, "Une erreur est survenue : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un emploi à supprimer !", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteEdtButtonActionPerformed
private void clearEdtFields() {
    idedtTextField.setText("");
    idsalleTextField.setText("");
    idprofTextField.setText("");
    idclasseTextField.setText("");
    coursTextField.setText("");
    dateSpinner.setValue(new Date()); // Réinitialise à la date actuelle
    /**
     * @param args the command line arguments
     */}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new edtViews().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEdtButton;
    private javax.swing.JTextField coursTextField;
    private javax.swing.JButton deleteEdtButton;
    private javax.swing.JButton editEdtbutton;
    private javax.swing.JTable edtTable;
    private javax.swing.JTextField idclasseTextField;
    private javax.swing.JTextField idedtTextField;
    private javax.swing.JTextField idprofTextField;
    private javax.swing.JTextField idsalleTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
