/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionedt.views;

/**
 *
 * @author diary
 */
import com.mycompany.gestionedt.controllers.ProfesseurControllers;
import javax.swing.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
import com.mycompany.gestionedt.models.ProfesseurModels ;

import java.util.ArrayList;

public class professeurViews extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(professeurViews.class.getName());

    /**
     * Creates new form professeurViews
     */
    public professeurViews() {
        initComponents();
        refreshTable();
        SearchProfTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            filterTable(); // Appelle la méthode de filtrage
        }
    });
    // Ajoute ceci à la fin
    filterTable(); // Affiche tous les prof
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idprofField = new javax.swing.JTextField();
        nameprofField = new javax.swing.JTextField();
        prenomField = new javax.swing.JTextField();
        addprofButton = new javax.swing.JButton();
        cancelprofButton = new javax.swing.JButton();
        gradeprofComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListProfTable = new javax.swing.JTable();
        EditProfButton = new javax.swing.JButton();
        DeleteProfButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SearchProfTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1850, 1001));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("ADD PROF");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Id Prof");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Grade");

        addprofButton.setBackground(new java.awt.Color(0, 204, 51));
        addprofButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addprofButton.setForeground(new java.awt.Color(255, 255, 255));
        addprofButton.setText("ADD");
        addprofButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addprofButtonActionPerformed(evt);
            }
        });

        cancelprofButton.setBackground(new java.awt.Color(255, 0, 0));
        cancelprofButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelprofButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelprofButton.setText("Cancel");

        gradeprofComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gradeprofComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Professeur Titulaire", "Maître de conference", "Assistant dEnseignant Superieur", "Docteur HDR", "Docteur e Infomatque", "Doctorant en informatique", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gradeprofComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(prenomField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameprofField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idprofField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(115, 115, 115)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(addprofButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(cancelprofButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idprofField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameprofField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prenomField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradeprofComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelprofButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addprofButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(208, 208, 208))
        );

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Les Professeurs");

        ListProfTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListProfTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ListProfTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Prof", "Nom", "Prenom", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ListProfTable.setPreferredSize(new java.awt.Dimension(300, 800));
        jScrollPane1.setViewportView(ListProfTable);

        EditProfButton.setBackground(new java.awt.Color(0, 102, 255));
        EditProfButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditProfButton.setForeground(new java.awt.Color(255, 255, 255));
        EditProfButton.setText("EDIT");
        EditProfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfButtonActionPerformed(evt);
            }
        });

        DeleteProfButton.setBackground(new java.awt.Color(255, 0, 0));
        DeleteProfButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteProfButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteProfButton.setText("DELETE");
        DeleteProfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProfButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Liste des Professeurs");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Search");

        SearchProfTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SearchProfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchProfTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(EditProfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(DeleteProfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SearchProfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(353, 353, 353))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(581, 581, 581))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchProfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EditProfButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(DeleteProfButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addprofButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addprofButtonActionPerformed
        // TODO add your handling code here:
        String idProf = idprofField.getText().trim();
        String NomProf = nameprofField.getText();
        String PrenomProf = prenomField.getText();
        String Grade = gradeprofComboBox.getSelectedItem() != null ? gradeprofComboBox.getSelectedItem().toString().trim() : "";

     if(!idProf.isEmpty() && !NomProf.isEmpty() && !PrenomProf.isEmpty() && !Grade.isEmpty()) {
        ProfesseurControllers controller = new ProfesseurControllers();
        
        if (addprofButton.getText().equals("Save")) {//verifie la cas
            // Mode mise à jour
            ProfesseurModels prof = new ProfesseurModels(idProf, NomProf, PrenomProf, Grade);
            controller.updateProfesseur(prof); // Nouvelle méthode pour la mise à jour
            JOptionPane.showMessageDialog(this, "Professeur mis à jour avec succès ! ID : " + idProf);
            addprofButton.setText("Ajouter"); // Revenir à Ajouter
            idprofField.setEditable(true); // Réactiver l'édition de idProf
        }else{
            // Mode ajout
            ProfesseurModels prof = controller.ajouterProfesseur(idProf, NomProf, PrenomProf, Grade);
            JOptionPane.showMessageDialog(this, "Professeur ajouté avec succès ! ID : " + prof.getIdProf());
        }
      
        idprofField.setText("");
        nameprofField.setText("");
        prenomField.setText("");
        gradeprofComboBox.setSelectedIndex(0);
        refreshTable();
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !", "Erreur", JOptionPane.ERROR_MESSAGE);
    
    }
        
                
    }//GEN-LAST:event_addprofButtonActionPerformed

    private void EditProfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = ListProfTable.getSelectedRow();
    if (selectedRow != -1) { // Vérifie qu'une ligne est sélectionnée
        DefaultTableModel model = (DefaultTableModel) ListProfTable.getModel();
        String idProf = model.getValueAt(selectedRow, 0).toString();
        String NomProf = model.getValueAt(selectedRow, 1).toString();
        String PrenomProf = model.getValueAt(selectedRow, 2).toString();
        String Grade = model.getValueAt(selectedRow, 3).toString();
        
        // Remplir le formulaire
        idprofField.setText(idProf);
        idprofField.setEditable(false); // Désactiver l'édition de idProf
        nameprofField.setText(NomProf);
        prenomField.setText(PrenomProf);
        gradeprofComboBox.setSelectedItem(Grade); // Assure-toi que les valeurs de la combo matchent
        
        addprofButton.setText("Save");
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un professeur à modifier !", "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_EditProfButtonActionPerformed

    private void DeleteProfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteProfButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = ListProfTable.getSelectedRow();
    if (selectedRow != -1) { // Vérifie qu'une ligne est sélectionnée
        DefaultTableModel model = (DefaultTableModel) ListProfTable.getModel();
        String idProf = model.getValueAt(selectedRow, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(this, "Êtes-vous sûr de vouloir supprimer le professeur avec ID " + idProf + " ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            ProfesseurControllers controller = new ProfesseurControllers();
            controller.deleteProfesseur(idProf); // Nouvelle méthode pour la suppression
            refreshTable(); // Rafraîchir la table après suppression
            JOptionPane.showMessageDialog(this, "Professeur supprimé avec succès !");
            }
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un professeur à supprimer !", "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_DeleteProfButtonActionPerformed

    private void SearchProfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchProfTextFieldActionPerformed
        // TODO add your handling code here:
        filterTable();
    }//GEN-LAST:event_SearchProfTextFieldActionPerformed
   
    
    
    
public void refreshTable(){
    ProfesseurControllers controller = new ProfesseurControllers();
    ArrayList<ProfesseurModels> professeurs = controller.getAllProfesseurs(); // Récupère la liste
    // Définir le modèle de la table
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Prof");
    model.addColumn("Nom");
    model.addColumn("Prénom");
    model.addColumn("Grade");

for (ProfesseurModels prof : professeurs) {
        model.addRow(new Object[]{
            prof.getIdProf(),
            prof.getNomProf(),
            prof.getPrenomProf(),
            prof.getGrade()
});
}

//appliquer la model du table

ListProfTable.setModel(model);
}

private void filterTable() {
    String searchText = SearchProfTextField.getText().trim().toLowerCase();
    ProfesseurControllers controller = new ProfesseurControllers();
    ArrayList<ProfesseurModels> allProfesseurs = controller.getAllProfesseurs();

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Prof");
    model.addColumn("Nom");
    model.addColumn("Prénom");
    model.addColumn("Grade");

    for (ProfesseurModels prof : allProfesseurs) {
        String nomProf = prof.getNomProf().toLowerCase();
        if (nomProf.contains(searchText)) { // Filtre par nom
            model.addRow(new Object[]{
                prof.getIdProf(),
                prof.getNomProf(),
                prof.getPrenomProf(),
                prof.getGrade()
            });
        }
    }

    ListProfTable.setModel(model);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
        java.awt.EventQueue.invokeLater(() -> {
        professeurViews view = new professeurViews();
        view.setVisible(true);
        view.refreshTable(); // Affiche la liste après ouverture
    });
    }
        
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteProfButton;
    private javax.swing.JButton EditProfButton;
    private javax.swing.JTable ListProfTable;
    private javax.swing.JTextField SearchProfTextField;
    private javax.swing.JButton addprofButton;
    private javax.swing.JButton cancelprofButton;
    private javax.swing.JComboBox<String> gradeprofComboBox;
    private javax.swing.JTextField idprofField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nameprofField;
    private javax.swing.JTextField prenomField;
    // End of variables declaration//GEN-END:variables

}
