/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionedt.views;

import com.mycompany.gestionedt.controllers.SalleControllers;
import com.mycompany.gestionedt.models.salleModels;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diary
 */
public class salleViews extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(salleViews.class.getName());

    /**
     * Creates new form salleViews
     */
    public salleViews() {
        initComponents();
        refreshSalleTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idSalleTextField = new javax.swing.JTextField();
        designTextField = new javax.swing.JTextField();
        occupationComboBox = new javax.swing.JComboBox<>();
        addSalleButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        salleTable = new javax.swing.JTable();
        editSalleButton = new javax.swing.JButton();
        deleteSalleButton = new javax.swing.JButton();
        afichesalleLibreButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1474, 1500));

        jLabel1.setText("Id Salle");

        jLabel2.setText("Design");

        jLabel3.setText("Occupation");

        occupationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Occupé", " " }));

        addSalleButton.setText("Add salle");
        addSalleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSalleButtonActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(designTextField)
                            .addComponent(idSalleTextField)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(occupationComboBox, 0, 279, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addSalleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(47, 47, 47))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idSalleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(designTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(occupationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSalleButton)
                    .addComponent(jButton2))
                .addGap(33, 33, 33))
        );

        salleTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        salleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id Salle", "Design", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(salleTable);

        editSalleButton.setText("jButton1");
        editSalleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSalleButtonActionPerformed(evt);
            }
        });

        deleteSalleButton.setText("jButton3");
        deleteSalleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSalleButtonActionPerformed(evt);
            }
        });

        afichesalleLibreButton.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(afichesalleLibreButton)
                                .addGap(44, 44, 44))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(536, 536, 536)
                        .addComponent(editSalleButton)
                        .addGap(79, 79, 79)
                        .addComponent(deleteSalleButton)))
                .addContainerGap(641, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(afichesalleLibreButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editSalleButton)
                            .addComponent(deleteSalleButton))
                        .addGap(252, 252, 252))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(353, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSalleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSalleButtonActionPerformed
        // TODO add your handling code here:
      String idSalle = idSalleTextField.getText().trim();
    String designStr = designTextField.getText().trim();
    String occupation = occupationComboBox.getSelectedItem() != null ? occupationComboBox.getSelectedItem().toString().trim() : "";

    if (!idSalle.isEmpty() && !designStr.isEmpty() && !occupation.isEmpty()) {
        try {
            int design = Integer.parseInt(designStr);

            SalleControllers controller = new SalleControllers();
            if (addSalleButton.getText().equals("Save")) {
                salleModels salle = new salleModels(idSalle, design, occupation);
                controller.updateSalle(salle);
                JOptionPane.showMessageDialog(this, "Salle mise à jour avec succès ! ID : " + idSalle);
                addSalleButton.setText("Ajouter");
                idSalleTextField.setEditable(true);
            } else {
                salleModels salle = controller.ajouterSalle(idSalle, design, occupation);
                JOptionPane.showMessageDialog(this, "Salle ajoutée avec succès ! ID : " + salle.getIdSalle());
            }

            idSalleTextField.setText("");
            designTextField.setText("");
            occupationComboBox.setSelectedIndex(0);
            refreshSalleTable();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Design doit être un nombre valide !", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !", "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_addSalleButtonActionPerformed

    private void editSalleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSalleButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = salleTable.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) salleTable.getModel();
            String idSalle = model.getValueAt(selectedRow, 0).toString();
            String designStr = model.getValueAt(selectedRow, 1).toString();
            String occupationStr = model.getValueAt(selectedRow, 2).toString();

            idSalleTextField.setText(idSalle);
            idSalleTextField.setEditable(false);
            designTextField.setText(designStr);
            occupationComboBox.setSelectedItem(occupationStr.equals("0") ? "Libre" : "Occupé");
            addSalleButton.setText("Save");
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une salle à modifier !", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editSalleButtonActionPerformed

    private void deleteSalleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSalleButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = salleTable.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) salleTable.getModel();
            String idSalle = model.getValueAt(selectedRow, 0).toString();

            int confirm = JOptionPane.showConfirmDialog(this, "Êtes-vous sûr de vouloir supprimer la salle avec ID " + idSalle + " ?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                SalleControllers controller = new SalleControllers();
                controller.deleteSalle(idSalle);
                refreshSalleTable();
                JOptionPane.showMessageDialog(this, "Salle supprimée avec succès !");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une salle à supprimer !", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteSalleButtonActionPerformed
private void refreshSalleTable() {
        SalleControllers controller = new SalleControllers();
    ArrayList<salleModels> salles = controller.getAllSalles();

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("id Salle");
    model.addColumn("Design");
    model.addColumn("Occupation");

    for (salleModels salle : salles) {
        model.addRow(new Object[]{
            salle.getIdSalle(),
            salle.getDesign(),
            salle.getOccupation() // Affiche directement la String
        });
    }

    salleTable.setModel(model);
    }
private void clearSalleFields() {
        idSalleTextField.setText("");
        designTextField.setText("");
        occupationComboBox.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new salleViews().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSalleButton;
    private javax.swing.JButton afichesalleLibreButton;
    private javax.swing.JButton deleteSalleButton;
    private javax.swing.JTextField designTextField;
    private javax.swing.JButton editSalleButton;
    private javax.swing.JTextField idSalleTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> occupationComboBox;
    private javax.swing.JTable salleTable;
    // End of variables declaration//GEN-END:variables
}
